version: '3'

services:
  redis-cluster:
    image: grokzen/redis-cluster:latest
    ports:
      - '26379-26384:26379-26384'
    environment:
      - 'INITIAL_PORT=26379'
      - 'MASTERS=3'
      - 'SLAVES_PER_MASTER=1'
      - 'SENTINEL=false'
      - 'REDIS_CLUSTER_IP=0.0.0.0'
      - 'IP=0.0.0.0'
      - 'BIND_ADDRESS=0.0.0.0'
